apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  selector:
    matchLabels:
      app: mongodb
      tier: mongodb
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
        tier: mongodb
        track: stable
    spec:
      containers:
        - name: db
          image: prakhar22/mongo1
          ports:
            - name: backend
              containerPort: 27017
          lifecycle:
            preStop:
              exec:
                command: ["mongosh"]
